---
apiVersion: v1
kind: Service
metadata:
  name: returnpath-task
spec:
  type: NodePort
  selector:
    app: returnpath-task
  ports:
    - name: http
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: returnpath-task
spec:
  selector:
    matchLabels:
      app: returnpath-task
  replicas: 1
  template:
    metadata:
      labels:
        app: returnpath-task
    spec:
      containers:
      - name: app
        image: cderwin/returnpath_task:latest
        ports:
        - containerPort: 8000
